# Generated by Django 5.2.4 on 2025-07-31 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='設定キー')),
                ('value', models.TextField(verbose_name='設定値')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'システム設定',
                'verbose_name_plural': 'システム設定',
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='アクション')),
                ('details', models.TextField(blank=True, verbose_name='詳細')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IPアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '管理ログ',
                'verbose_name_plural': '管理ログ',
                'ordering': ['-created_at'],
            },
        ),
    ]
