"""
URL configuration for aichat project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/http/urls/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

# 管理画面のカスタマイズ
admin.site.site_header = getattr(settings, 'ADMIN_SITE_HEADER', 'AIチャット管理')
admin.site.site_title = getattr(settings, 'ADMIN_SITE_TITLE', 'AIチャット管理画面')
admin.site.index_title = getattr(settings, 'ADMIN_INDEX_TITLE', '管理画面')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
    path('panel/', include('admin_panel.urls')),
]
